

services:
  db:
    image: mysql:8.0
    container_name: oms_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_db
      MYSQL_USER: jenny
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: oms_app
    depends_on:
      - db
    environment:
      # 指向 db 服務，注意 host 改為 `db`
      DATABASE_URL: mysql+pymysql://jenny:1234@db:3306/my_db
      SECRET_KEY: your-secret-key
      JWT_SECRET_KEY: your-jwt-secret
      FLASK_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - .:/app      # 開發模式：本地程式碼變動即時生效
    command: flask run --host=0.0.0.0

volumes:
  db_data:
