"""Add total_price to orders and order_items table

Revision ID: b533a0c41d82
Revises: 5cbf2a94f78f
Create Date: 2025-05-27 11:10:30.848546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b533a0c41d82'
down_revision = '5cbf2a94f78f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
